scrape_configs:
  - job_name: 'springboot'
    scheme: http # for localhost
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['127.0.0.1:8080']
